openapi: 3.0.1
info:
  title: Shoppin&Go Inventory API
  version: 1.0.0
servers:
- url: http://localhost
tags:
- name: DeviceConnection
  description: 기기와 카트를 연관할 때 사용하는 API 입니다
- name: ErrorHandling
  description: 예외 처리가 필요한 API 입니다
paths:
  /cart-connections:
    post:
      tags:
      - ErrorHandling
      - DeviceConnection
      summary: 기기와 카트를 연결합니다.
      description: 기기와 카트를 연결합니다.
      operationId: ConnectToCart
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/ConnectToCartRequest'
            examples:
              ConnectToCart_CartNotFoundException:
                value: "{\"deviceId\":\"device-test_ead7d9b5-b9ca-4e7c-9e9f-debfa43d260b\"\
                  ,\"cartCode\":\"cart-test_4e7c12e5-2448-4c25-a1fa-29f8beb0eb28\"\
                  }"
              ConnectToCart_DeviceAlreadyConnectedException:
                value: "{\"deviceId\":\"device-test_764eca46-cf30-473c-976a-a3fee7fa63b1\"\
                  ,\"cartCode\":\"cart-test_54212b04-25b9-492f-aed8-701a6a8291ec\"\
                  }"
              ConnectToCart_CartAlreadyConnectedException:
                value: "{\"deviceId\":\"device-test_5f73fa80-df12-475b-b4cb-8886363348d8\"\
                  ,\"cartCode\":\"cart-test_c2b89b76-6483-4afe-8c67-6390f92bfad6\"\
                  }"
              ConnectToCart:
                value: "{\"deviceId\":\"device-test_47c01ad3-e90d-4016-811f-99980c981990\"\
                  ,\"cartCode\":\"cart-test_603d65e4-cf7d-4c51-8ea1-21bfddad95ba\"\
                  }"
      responses:
        "400":
          description: "400"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                ConnectToCart_CartNotFoundException:
                  value: "{\"code\":\"ERROR\",\"message\":\"Cart not found: cart-test_4e7c12e5-2448-4c25-a1fa-29f8beb0eb28\"\
                    ,\"result\":{}}"
        "409":
          description: "409"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                ConnectToCart_DeviceAlreadyConnectedException:
                  value: "{\"code\":\"ERROR\",\"message\":\"This device is already\
                    \ connected with another cart\",\"result\":{}}"
                ConnectToCart_CartAlreadyConnectedException:
                  value: "{\"code\":\"ERROR\",\"message\":\"This cart is already connected\
                    \ with another device\",\"result\":{}}"
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartConnectionStatus'
              examples:
                ConnectToCart:
                  value: "{\"code\":\"OK\",\"message\":\"Success\",\"result\":{\"\
                    connection\":{\"cartCode\":\"cart-test_603d65e4-cf7d-4c51-8ea1-21bfddad95ba\"\
                    ,\"connectedAt\":\"2024-10-19T06:46:54\",\"connected\":true}}}"
  /devices/{deviceId}/cart-connections:
    get:
      tags:
      - DeviceConnection
      summary: 기기의 카트 연결 히스토리를 조회합니다.
      description: 기기의 카트 연결 히스토리를 조회합니다.
      operationId: ListCartConnections
      parameters:
      - name: deviceId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartConnectionStatusList'
              examples:
                ListCartConnections:
                  value: "{\"code\":\"OK\",\"message\":\"Success\",\"result\":{\"\
                    connections\":[{\"cartCode\":\"cart-test_b01e3226-7b90-4a07-8eb4-d126de5a354e\"\
                    ,\"connectedAt\":\"2024-10-19T06:46:54\",\"connected\":false},{\"\
                    cartCode\":\"cart-test_dc3c49d6-72bf-4068-af73-fb4622993326\"\
                    ,\"connectedAt\":\"2024-10-19T06:46:54\",\"connected\":true}]}}"
    delete:
      tags:
      - DeviceConnection
      summary: 기기의 카트 연결을 모두 해제합니다.
      description: 기기의 카트 연결을 모두 해제합니다.
      operationId: DisconnectFromAllCarts
      parameters:
      - name: deviceId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartConnectionStatusList'
              examples:
                DisconnectFromAllCarts:
                  value: "{\"code\":\"OK\",\"message\":\"Success\",\"result\":{\"\
                    connections\":[{\"cartCode\":\"cart-test_b838cdaf-8e54-48cd-8761-b855cafffbab\"\
                    ,\"connectedAt\":\"2024-10-19T06:46:55\",\"connected\":false},{\"\
                    cartCode\":\"cart-test_d6916dcd-081e-4e0d-8b7b-3a80dd91889b\"\
                    ,\"connectedAt\":\"2024-10-19T06:46:55\",\"connected\":false}]}}"
components:
  schemas:
    CartConnectionStatusList:
      title: CartConnectionStatusList
      type: object
      properties:
        result:
          type: object
          properties:
            connections:
              type: array
              description: 카트 연결 히스토리
              items:
                type: object
                properties:
                  connected:
                    type: boolean
                    description: 연결 여부
                  cartCode:
                    type: string
                    description: 카트 코드
                  connectedAt:
                    type: string
                    description: 연결 시간
        code:
          type: string
          description: 응답 코드
        message:
          type: string
          description: 응답 메시지
    ConnectToCartRequest:
      title: ConnectToCartRequest
      type: object
      properties:
        cartCode:
          type: string
          description: 카트 코드
        deviceId:
          type: string
          description: 디바이스 ID
    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        result:
          type: object
          description: 빈 객체
        code:
          type: string
          description: 응답 코드
        message:
          type: string
          description: 오류 메시지
    CartConnectionStatus:
      title: CartConnectionStatus
      type: object
      properties:
        result:
          type: object
          properties:
            connection:
              type: object
              properties:
                connected:
                  type: boolean
                  description: 연결 여부
                cartCode:
                  type: string
                  description: 연결된 카트 코드
                connectedAt:
                  type: string
                  description: 연결 시간
        code:
          type: string
          description: 응답 코드
        message:
          type: string
          description: 응답 메시지
