name: Publish API Spec

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_oas3:
    runs-on: ubuntu-latest
    env:
      API_DOCS_DIR: api-docs
      BUILD_OUTPUT_PATH: build/api-spec/openapi3.yaml
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          cache: 'gradle'

      - name: Generate OpenAPI 3 Spec
        run: ./gradlew clean openapi3

      - name: Clone Swagger UI
        run: |
          git clone https://github.com/swagger-api/swagger-ui.git
          mkdir -p ./swagger-ui/dist ./${{ env.API_DOCS_DIR }}
          cp -r ./swagger-ui/dist/* ./${{ env.API_DOCS_DIR }}

      - name: Copy OpenAPI file
        run: cp ${{ BUILD_OUTPUT_PATH }} ./${{ env.API_DOCS_DIR }}/openapi3.yaml

      - name: Update oas3 file path in index.html
        run: |
          sed -i 's|url: "https://petstore.swagger.io/v2/swagger.json"|url: "./openapi3.yaml"|' ./${{ env.API_DOCS_DIR }}/swagger-initializer.js

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
