name: Publish API Spec

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_oas3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          cache: 'gradle'

      - name: Generate OpenAPI 3 Spec
        run: ./gradlew clean openapi3

      - name: Clear and create docs directory
        run: |
          rm -rf ./docs
          mkdir ./docs

      - name: Clone Swagger UI
        run: |
          git clone https://github.com/swagger-api/swagger-ui.git
          mkdir -p ./swagger-ui/dist
          cp -r ./swagger-ui/dist/* ./docs/

      - name: Copy OpenAPI file
        run: cp build/api-spec/openapi3.yaml ./docs/api-docs.yaml

      - name: Update oas3 file path in index.html
        run: |
          sed -i 's|url: "https://petstore.swagger.io/v2/swagger.json"|url: "./api-docs.yaml"|' ./docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs