name: Publish API Spec

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_oas3:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          cache: 'gradle'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate OpenAPI 3 Spec
        run: ./gradlew clean openapi3

      - name: Set output for OpenAPI file path
        id: set_output
        run: echo "oas3_file_path=$(pwd)/build/api-spec/openapi3.yaml" >> $GITHUB_ENV

  deploy_swagger_ui:
    runs-on: ubuntu-latest
    needs: build_oas3  # build_oas3 작업이 완료된 후 실행
    steps:
      - name: Clone Swagger UI
        run: |
          git clone https://github.com/swagger-api/swagger-ui.git
          mkdir -p ./swagger-ui/dist
          cp -r ./swagger-ui/dist/* ./docs/

      - name: Copy OpenAPI file
        run: cp ${{ env.oas3_file_path }} ./docs/api-docs.yaml

      - name: Update oas3 file path in index.html
        run: |
          sed -i 's|url: "https://petstore.swagger.io/v2/swagger.json"|url: "./api-docs.yaml"|' ./docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs