name: Deployment

on:
  workflow_run:
    workflows:
      - Integration
    branches:
      - main
    types:
      - completed
permissions:
  id-token: write
  contents: read
jobs:
  publish:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::309327648043:role/ecr-deploy
          aws-region: us-east-1
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          cache: 'gradle'
      - name: Build and push image to Amazon ECR
        run: ./gradlew clean jib -x test
  deploy:
    name: Deploy to AWS ECS
    runs-on: ubuntu-latest
    needs: [ deploy_ecr ]
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::309327648043:role/ecr-deploy
          aws-region: ap-northeast-2
      - name: Deploy to AWS ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: task-definition.json
          cluster: shoppin-and-go-cluster
          service: inventory-api
          wait-for-service-stability: true
