name: Deployment

on:
  workflow_run:
    workflows:
      - Integration
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::309327648043:role/ecr-deploy
          aws-region: aws-northeast-2
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'corretto'
          cache: 'gradle'
      - name: Build and push image to Amazon ECR
        run: ./gradlew clean jib -x test
#      - name: Deploy to AWS ECS
#        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
#        with:
#          task-definition: task-definition.json
#          cluster: <ECS_CLUSTER_NAME>
#          service: <ECS_SERVICE_NAME>
#          wait-for-service-stability: true